### ISSUE TITLE
Adjust map record description field

### ISSUE THREAD

**Issue by bensinjin** [PeaceGeeks/amani#684]
according to the following spec:

anon users cannot use rich text

auth users can use rich text 

the field in the “summary” for the popup on the  map will be cleaned/trimmed version of the description
	
the description on the node view will be rich text

**Comment by bensinjin** [comment]
@PeaceGeeks this has been addressed see dev.

**Comment by PeaceGeeks** [comment]
So this works fine now for authenticated users - tho I really think we need to improve the theming of the Map Record page - but I still have the same problem (of not being being able to use the key strokes) when a an Anonymous user submits a records and then an Authenticated user goes to try to edit the 'Description'

**Comment by MagdiRizkallah** [comment]
I do not see the option for rich text editor with all the icons at the top (as in body editing on other content types)

**Comment by ZoeAffinity** [comment]
The keystrokes thing can be fixed by changing the field group style from "accordion" to some other style, eg plain divs or vertical tabs.

**Comment by MagdiRizkallah** [comment]
@ZoeAffinity as you can see from the screen shot above, it is not accordion style anymore.  There must be some other reason for Map records content type...

**Comment by ZoeAffinity** [comment]
It's not accordion style on dev right now, because I changed it to Vertical Tabs style, so that people can see that it fixes the issue Renee reported with the arrow keys not working.

**Comment by bensinjin** [comment]
@MagdiRizkallah @PeaceGeeks I've emailed you guys outlining somethings I would like to try, please take a look when you have a chance - I'm hoping it will address all the issues around the map record creation.

**Comment by PeaceGeeks** [comment]
@bensinjin - the map does not display

**Comment by bensinjin** [comment]
what?

**Comment by MagdiRizkallah** [comment]
I like the standardization (similar to any other content type editing)...  However there is a duplicate set of Map icons as shown below
![image](https://cloud.githubusercontent.com/assets/5035201/6311497/5c3171d0-b918-11e4-8173-d750990f4328.png)

**Comment by PeaceGeeks** [comment]
Yes - I also tested this yesterday after the doubling of the icons was fixed, and it was fine at first, but when I clicked the 'Find address' button, the icons doubled again.

**Comment by PeaceGeeks** [comment]
Also, can we create a hover label for those icons? ''Polygon", 'Map Pointer' and 'Move Map' and put the default in the first position?

**Comment by PeaceGeeks** [comment]
And/ or somehow make it more obvious that that is the tool that is actively in use on the map? This is definitely not very intuitive for users

**Comment by MagdiRizkallah** [comment]
verified
